# Setup
title:        PestDetective
tagline:      An AI powered pest control solution 
baseurl:      iottrap.github.io"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Manan Luthra
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown